### PR TITLE
updated support page for new bugs

### PR DESCRIPTION
**Pull request by teresas**
updated support page so people submit github issues instead of JIRAs

### CODE REVIEW

**Comment by teresas** [comment]
It looks like the page in the repo doesn't match the live page (support mailing lists section is different and doesn't reflect new mailing lists), so I'm guessing the page was edited out of version control again. @bester  Would it be possible for you to edit the live page and then commit it to git so it's updated?

**Comment by bester** [comment]
I copied the live page to git

**Comment by teresas** [comment]
Thanks! Can you still use this pull request or should I check out a new branch using the new file and submit a new one?

**Comment by bester** [comment]
This one is fine.

Joe

**Pull request merged**
